=== craigcondit/randomcoder-website/WEB-INF/test/test-data.dtd
<!ELEMENT dataset (
    users*,
    roles*,
    user_role_link*,
    articles*,
    tags*,
    article_tag_link*,
    comments*)>

<!ELEMENT users EMPTY>
<!ATTLIST users
    user_id CDATA #REQUIRED
    username CDATA #REQUIRED
    password CDATA #REQUIRED
    email CDATA #REQUIRED
    enabled CDATA #REQUIRED
>

<!ELEMENT roles EMPTY>
<!ATTLIST roles
    role_id CDATA #REQUIRED
    name CDATA #REQUIRED
    description CDATA #IMPLIED
>

<!ELEMENT user_role_link EMPTY>
<!ATTLIST user_role_link
    user_id CDATA #REQUIRED
    role_id CDATA #REQUIRED
>

<!ELEMENT articles EMPTY>
<!ATTLIST articles
    article_id CDATA #REQUIRED
    content_type CDATA #REQUIRED
    create_user_id CDATA #IMPLIED
    create_date CDATA #REQUIRED
    modify_user_id CDATA #IMPLIED
    modify_date CDATA #IMPLIED
    title CDATA #REQUIRED
    permalink CDATA #IMPLIED
    content CDATA #REQUIRED
    summary CDATA #IMPLIED
>

<!ELEMENT tags EMPTY>
<!ATTLIST tags
    tag_id CDATA #REQUIRED
    name CDATA #REQUIRED
    display_name CDATA #REQUIRED
>

<!ELEMENT article_tag_link EMPTY>
<!ATTLIST article_tag_link
    article_id CDATA #REQUIRED
    tag_id CDATA #REQUIRED
>

<!ELEMENT comments EMPTY>
<!ATTLIST comments
    comment_id CDATA #REQUIRED
    article_id CDATA #REQUIRED
    content_type CDATA #REQUIRED
    create_user_id CDATA #IMPLIED
    create_date CDATA #REQUIRED
    anonymous_user_name CDATA #IMPLIED
    anonymous_email_address CDATA #IMPLIED
    anonymous_website CDATA #IMPLIED
    title CDATA #REQUIRED
    content CDATA #REQUIRED
>

=== craigcondit/randomcoder-website/WEB-INF/test/test-data.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "test-data.dtd">
<dataset>
  <users/>
  <roles role_id="1" name="manage-users" description="Manage users"/>
  <roles role_id="2" name="article-post" description="Post articles"/>
  <roles role_id="3" name="article-admin" description="Update other users&apos; articles"/>
  <roles role_id="4" name="development-dwr" description="DWR Testing"/>
  <roles role_id="5" name="manage-tags" description="Manage tags"/>
  <roles role_id="6" name="manage-comments" description="Manage comments"/>
  <user_role_link/>
  <articles/>
  <tags/>
  <article_tag_link/>
  <comments/>
</dataset>
